### PR TITLE
Add remote modules support for OTB nixpkgs

### PR DESCRIPTION
**Pull request by daspk04**
This allows OTB NixPkgs to be built with several remote modules.

### CODE REVIEW

**Comment by daspk04** [comment]
Check regarding LICENSE, may be ask in OTB gitlab and OTBTF :

- What should be the LICENSE if one is building all from the source ?  [some ref](https://www.orfeo-toolbox.org/CookBook/RemoteModules.html) 
- Possibly add a LICENSE for each of those remote modules separately file similar to how it is done in official [OTB GitLab](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/-/blob/develop/Modules/Remote/S1TilingSupportApplications.remote.cmake?ref_type=heads), in that case one has to prepare a separate nix file or json file for each remote module and LICENSE at the beginning of the file.

**Comment by remicres** [comment]
Hi @daspk04 I just saw that Mosaic remote module is now deprecated (as part of the OTB now). I am preparing a PR to OTB repo. Regarding the license of otbtf, it is the same as OTB (Apache 2.0) except that INRAE is the owner, not CNES

**Comment by daspk04** [comment]
> Hi @daspk04 I just saw that Mosaic remote module is now deprecated (as part of the OTB now). I am preparing a PR to OTB repo. Regarding the license of otbtf, it is the same as OTB (Apache 2.0) except that INRAE is the owner, not CNES

Thanks @remicres!

Will it possible if you can also confirm if source are correct or should be modified:

- OBTF, simpleextractiontools, otb-mlutils : https://forgemia.inra.fr/ 
- GRM, LSGRM, TimeSeriesUtils, TemporalSmoothing : https://gitlab.irstea.fr/remi.cresson/
- otbPrefetch: https://github.com/remicres/otb-prefetch.git (also available at https://forgemia.inra.fr/ but github one seems like one commit ahead)

LSGRM: The last updated one seems to be in a separate branch named `disassembled`

**Comment by remicres** [comment]
I just have contacted the LSGRM devs to ask them (I don't have followed this project for a while).
A few years ago, inra and irstea have merged (into "inrae") so we will likely have an unique gitlab instance soon... but we don't know when exactly (probably around early 2025). So a lot of these repositories are mirrored, and you can safely use either gitlab.irstea.fr of forgemia.inra.fr at this point (If you have doubt, best is to rely on forgemia.inra.fr though, because it is a bit more stable). I have put otbtf, prefetch, simpleextractiontools, mlutils, and more here https://forgemia.inra.fr/orfeo-toolbox/, I'll do the same after the migration on the future inrae's gitlab

**Comment by daspk04** [comment]
> I just have contacted the LSGRM devs to ask them (I don't have followed this project for a while). A few years ago, inra and irstea have merged (into "inrae") so we will likely have an unique gitlab instance soon... but we don't know when exactly (probably around early 2025). So a lot of these repositories are mirrored, and you can safely use either gitlab.irstea.fr of forgemia.inra.fr at this point (If you have doubt, best is to rely on forgemia.inra.fr though, because it is a bit more stable). I have put otbtf, prefetch, simpleextractiontools, mlutils, and more here https://forgemia.inra.fr/orfeo-toolbox/, I'll do the same after the migration on the future inrae's gitlab

Thanks @remicres ! 

So then the source I think I have put are correct. I will update LSGRM incase there is any update later. I'll merge this one.

**Pull request merged**
